import { IconType } from "react-icons";
import {
  HiOutlineSquares2X2,
  HiOutlineEye,
  HiOutlineCalendarDays,
  HiOutlineUsers,
  HiOutlineChartBarSquare,
  HiOutlineRocketLaunch,
  HiOutlineCog6Tooth,
  HiOutlineArrowRightOnRectangle,
  HiOutlineTrash,
  HiOutlinePlusCircle,
  HiOutlineMinusCircle,
  HiOutlineWallet,
  HiOutlineArrowDownTray,
  HiOutlineBriefcase,
  HiOutlineArrowPath,
  HiOutlineArrowTrendingUp,
  HiOutlineArrowTrendingDown,
  HiOutlineChartPie,
  HiOutlineBolt,
  HiOutlineSparkles,
  HiOutlineCpuChip,
  HiOutlineSignal,
  HiOutlineCurrencyDollar,
  HiOutlineBanknotes,
  HiOutlineArrowUp,
  HiOutlineArrowDown,
  HiOutlineClock,
  HiOutlineQrCode,
  HiOutlineCheckBadge,
  HiOutlineCreditCard,
  HiOutlineReceiptRefund,
  HiOutlineGlobeAlt,
  HiOutlineKey,
  HiOutlinePresentationChartLine,
  HiOutlineArrowsRightLeft,
  HiOutlineCommandLine,
  HiOutlineBars3BottomLeft,
} from "react-icons/hi2";

export const iconLibrary: Record<string, IconType> = {
  dashboard: HiOutlineSquares2X2,
  watchlist: HiOutlineEye,
  calendar: HiOutlineCalendarDays,
  users: HiOutlineUsers,
  quota: HiOutlineChartBarSquare,
  finance: HiOutlineWallet,
  portfolio: HiOutlineBriefcase,
  transactions: HiOutlineArrowPath,
  rocket: HiOutlineRocketLaunch,
  settings: HiOutlineCog6Tooth,
  logout: HiOutlineArrowRightOnRectangle,
  trash: HiOutlineTrash,
  add: HiOutlinePlusCircle,
  remove: HiOutlineMinusCircle,
  download: HiOutlineArrowDownTray,
  trendingUp: HiOutlineArrowTrendingUp,
  trendingDown: HiOutlineArrowTrendingDown,
  chartPie: HiOutlineChartPie,
  bolt: HiOutlineBolt,
  sparkles: HiOutlineSparkles,
  cpuChip: HiOutlineCpuChip,
  signal: HiOutlineSignal,
  currencyDollar: HiOutlineCurrencyDollar,
  banknotes: HiOutlineBanknotes,
  arrowUp: HiOutlineArrowUp,
  arrowDown: HiOutlineArrowDown,
  clock: HiOutlineClock,
  qrCode: HiOutlineQrCode,
  checkBadge: HiOutlineCheckBadge,
  creditCard: HiOutlineCreditCard,
  receiptRefund: HiOutlineReceiptRefund,
  globeAlt: HiOutlineGlobeAlt,
  key: HiOutlineKey,
  presentationChartLine: HiOutlinePresentationChartLine,
  arrowsRightLeft: HiOutlineArrowsRightLeft,
  commandLine: HiOutlineCommandLine,
  menu: HiOutlineBars3BottomLeft,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
